---
name: Enforce Jira Issue on PR message

on:
  pull_request:
    types: [opened, edited, reopened]
jobs:
  update_pr:
    runs-on: ubuntu-20.04
    steps:  
      - name: Try to update the PR title with Jira Issue from source branch
        uses: tzkhan/pr-update-action@bbd4c9395df8a9c4ef075b8b7fe29f2ca76cdca9
        id: update_title
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          head-branch-regex: '[A-Z][A-Z0-9]+-[0-9]+'
          title-template: '[%headbranch%] '
        
      - name: Enforce Jira Issue Key in PR title
        uses: ryanvade/enforce-pr-title-style-action@6219de5d10b3205f0b41215bdf51a01b89bd8a1b