# Triggers when a branch is created, if the branch is an `rc` branch, then trigger all the build workflows
---
name: RC Listener

on:
  create: {}  # create: doesn't support branch/tag filtering


jobs:
  call-web-build:
    if: ${{ endsWith(github.ref, 'rc') }}
    uses: bitwarden/clients/.github/workflows/build-web.yml@${{ github.ref_name }}
